redis:
  image: redis
  container_name: cache
  expose:
    - 6379

app:
  links:
    - redis
  build: ./
  ports:
    - 8000:8000
  environment:
    - NODE_ENV=development
    - NODE_PORT=8000
    - REDIS_URL=redis://cache
  command:
    sh -c 'npm i && node .'
